os: windows
language: sh
python: 2.7
before_install:
    - choco install python2
    - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
    - python -m pip install --upgrade pip wheel
install:
    pip install shellfoundry
script:
    - shellfoundry pack
    - mkdir dep
    - pip download -r src/requirements.txt -d dep
    - zip -r dep.zip dep/*
